name: main job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: github-actions-sample
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: gradle build
        run: ./gradlew build
      - name: docker
        env:
          AUTH_TOKEN: {{secrets.GITHUB_TOKEN}}
        run: |
          docker login docker.pkg.github.com --username iljun -p $AUTH_TOKEN
          docker build . -t docker.pkg.github.com/iljun/actions-sample/github-actions:0.0.1
          docker push docker.pkg.github.com/iljun/actions-sample/github-actions:0.0.1