name: main job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: github-actions-sample
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: gradle build
        run: ./gradlew build
      - name: docker login
        run: docker login docker.pkg.github.com --username iljun -p {{secrets.GITHUB_TOKEN}}
      - name: docker build
        run: docker build . -t docker.pkg.github.com/iljun/actions-sample/github-actions:$GITHUB_SHA
      - name: docker push
        run: docker push docker.pkg.github.com/iljun/actions-sample/github-actions:$GITHUB_SHA