name: main job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: github-actions-sample
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: gradle build
        run: ./gradlew build
      - name: docker
        run: |
          docker login docker.pkg.github.com --username iljun -p {{secrets.GITHUB_TOKEN}}
          docker build . -t docker.pkg.github.com/iljun/actions-sample/app:latest
          docker push docker.pkg.github.com/iljun/actions-sample/app:latest