name: main job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: github-actions-sample
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: gradle build
        run: ./gradlew build
      - name: docker build
        run: docker build . -t docker.pkg.github.com/iljun/actions-sample/github-actions:0.0.1
      - name: docker publish
        uses: elgohr/Publish-Docker-Github-Action@2.10
        with:
          name: iljun/github-actions
          username: iljun
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com